"""
Trade Decision Centre Service
Receives and logs trade analysis from trading bots.
"""

import logging
from typing import Any, Dict, Optional
from datetime import datetime
import asyncio
from fastapi import BackgroundTasks

from app.schemas.trading_bot import OIAnalysisResult
from app.db.mongodb import MongoDB
from app.services.signal_analysis import analyze_trade_signal
from app.services.email_service import email_service

logger = logging.getLogger(__name__)

class TradeDecisionCentre:
    """
    Central service for receiving and processing trade analysis from bots.
    """
    
    def __init__(self):
        pass

    async def log_analysis(self, analysis: OIAnalysisResult, background_tasks: Optional[BackgroundTasks] = None) -> None:
        """
        Log the received trade analysis and send email notifications if signal is generated.
        
        Args:
            analysis: The analysis result from a trading bot.
            background_tasks: FastAPI BackgroundTasks object (optional).
        """
        try:
            # Calculate signal using the new service
            trade_signal = analyze_trade_signal(analysis)
            
            logger.info(f"\n{'='*80}")
            logger.info(f"🏢 TRADE DECISION CENTRE RECEIVED ANALYSIS")
            logger.info(f"{'='*80}")
            logger.info(f"Bot ID: {analysis.instrument_key}") # Using instrument key as proxy for bot source for now
            logger.info(f"Bot Signal: {analysis.signal}")
            logger.info(f"TDC Signal: {trade_signal}")
            logger.info(f"PCR: {analysis.pcr_oi}")
            logger.info(f"Call OI Change: {analysis.total_call_oi_change}")
            logger.info(f"Put OI Change: {analysis.total_put_oi_change}")
            
            logger.info(f"\n--- Strike Analysis ---")
            logger.info(f"{'Strike':<10} | {'Call OI Chg':<15} | {'Put OI Chg':<15}")
            logger.info("-" * 46)
            
            strike_details = ""
            for strike in analysis.strikes_analyzed:
                line = (
                    f"{strike.strike_price:<10.2f} | "
                    f"{strike.call_oi_change:<15} | "
                    f"{strike.put_oi_change:<15}"
                )
                logger.info(line)
                strike_details += f"<tr><td>{strike.strike_price}</td><td>{strike.call_oi_change}</td><td>{strike.put_oi_change}</td></tr>"

            logger.info(f"{'='*80}\n")
            
            # --- Store Signal Count ---
            current_counts = await self._update_signal_count(analysis.instrument_key, trade_signal)
            
            # --- Send Email Notification if Valid Signal ---
            if "BULLISH" in trade_signal or "BEARISH" in trade_signal:
                # Construct Email Body
                try:
                    email_subject = f"📢 Trade Signal: {trade_signal} - {analysis.instrument_key}"
                    
                    # Basic counts display
                    counts_html = ""
                    if current_counts:
                        counts_html = f"""
                        <h3>Daily Signal Counts ({current_counts.get('date', 'Today')})</h3>
                        <ul>
                            <li>Bullish Push: {current_counts.get('bullish_push_count', 0)}</li>
                            <li>Bullish Accumulation: {current_counts.get('bullish_accumulation_count', 0)}</li>
                            <li>Bearish Push: {current_counts.get('bearish_push_count', 0)}</li>
                            <li>Bearish Accumulation: {current_counts.get('bearish_accumulation_count', 0)}</li>
                        </ul>
                        """

                    email_body = f"""
                    <h2>Trade Signal Alert</h2>
                    <p><strong>Signal:</strong> <span style="font-size: 1.2em; color: {'green' if 'BULLISH' in trade_signal else 'red'};">{trade_signal}</span></p>
                    <p><strong>Instrument:</strong> {analysis.instrument_key}</p>
                    <p><strong>PCR:</strong> {analysis.pcr_oi}</p>
                    <p><strong>Total Call OI Change:</strong> {analysis.total_call_oi_change}</p>
                    <p><strong>Total Put OI Change:</strong> {analysis.total_put_oi_change}</p>
                    
                    {counts_html}
                    
                    <h3>Strike Price Analysis</h3>
                    <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
                        <thead>
                            <tr>
                                <th>Strike</th>
                                <th>Call OI Chg</th>
                                <th>Put OI Chg</th>
                            </tr>
                        </thead>
                        <tbody>
                            {strike_details}
                        </tbody>
                    </table>
                    <p><small>Generated by TradeLit Trade Decision Centre at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</small></p>
                    """

                    if background_tasks:
                        logger.info("Scheduling email in BackgroundTasks...")
                        background_tasks.add_task(email_service.send_email, email_subject, email_body)
                    else:
                        logger.info("Sending email via asyncio.create_task...")
                        asyncio.create_task(email_service.send_email(email_subject, email_body))
                except Exception as ex:
                     logger.error(f"❌ Error preparing/sending email: {str(ex)}")

        except Exception as e:
            logger.error(f"❌ Error logging analysis in Trade Decision Centre: {str(e)}")

    async def _update_signal_count(self, instrument_key: str, signal: str) -> Optional[Dict[str, Any]]:
        """
        Update the daily signal count in the database and return the updated counts.
        """
        try:
            today_str = datetime.now().strftime("%Y-%m-%d")
            collection = MongoDB.get_collection("daily_signal_counts")
            
            update_field = None
            if "BULLISH PUSH" in signal:
                update_field = "bullish_push_count"
            elif "BULLISH ACCUMULATION" in signal:
                update_field = "bullish_accumulation_count"
            elif "BEARISH PUSH" in signal:
                update_field = "bearish_push_count"
            elif "BEARISH ACCUMULATION" in signal:
                update_field = "bearish_accumulation_count"
                
            if update_field:
                await collection.update_one(
                    {"date": today_str, "instrument_key": instrument_key},
                    {
                        "$inc": {update_field: 1},
                        "$set": {"last_updated_at": datetime.utcnow()}
                    },
                    upsert=True
                )
                
            # Fetch updated counts (always fetch to return current state even if no update)
            doc = await collection.find_one({"date": today_str, "instrument_key": instrument_key})
            
            if doc:
                logger.info(f"📊 Daily Signal Count ({today_str}):")
                logger.info(f"   Bullish Push: {doc.get('bullish_push_count', 0)}")
                logger.info(f"   Bullish Accum: {doc.get('bullish_accumulation_count', 0)}")
                logger.info(f"   Bearish Push: {doc.get('bearish_push_count', 0)}")
                logger.info(f"   Bearish Accum: {doc.get('bearish_accumulation_count', 0)}")
                return doc
            return None

        except Exception as e:
            logger.error(f"❌ Error updating signal count: {str(e)}")
            return None

# Singleton instance
trade_decision_centre = TradeDecisionCentre()
